### PR TITLE
Fix/cypress test

### LINKED ISSUE #6: Cypress Testing
- [ ] all user flows covered
 - [ ] Async functionality is stubbed at least once

### PR DESCRIPTION
**Pull request by rhen92**
## Description
Please include a summary of the change and which issue is fixed. Please also include relevant screenshots of your code being deployed. 
- Fix some cypress tests with tags on Login/Signup being changed
- Update detailpage tests for shiny/regular form button and for removing header

Fixes # (issue)
- Closes #6

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: cypress/integration/signup_spec.js [hunk 1]
```diff
@@ -75,16 +75,16 @@ describe('Sign up', () => {
       .get('button').click()
       .get('form input[type="email"]:invalid')
   })
-  
-  it.only('should say loading while retreving the data', () => {
```
Comment (Thee-Dust) [inline cypress/integration/signup_spec.js:79]: good job finding the .only

File: cypress/integration/detailpage_spec.js [hunk 2]
```diff
@@ -62,18 +56,20 @@ describe('Detail page', () => {
...
   it('should have ivysaur info', () => {
     cy.wait(1000)
-      .get('a').eq(2).click()
+      .get('a').click()
       .get('.pokemon-card').eq(1).click()
       .url().should('eq', 'http://localhost:3000/2')
       .get('.info-header > a')
       .get('h1').contains('IVYSAUR')
+      .get('button').contains('Regular Form')
+      .get('button').contains('Shiny Form')
```
Comment (asiisii) [inline cypress/integration/detailpage_spec.js:72]: thanks for updating the test with new buttons

**Review by asiisii — APPROVED** [review]
